export interface WordPairs {
    word1: string;
    word2: string;
}

export const wordS: WordPairs[] = [

    { word1: "pomme", word2: "poire" },
    { word1: "pomme", word2: "banane" },
    { word1: "chat", word2: "tigre" },
    { word1: "chat", word2: "chien" },
    { word1: "plage", word2: "désert" },
    { word1: "plage", word2: "oasis" },
    { word1: "Coca Cola", word2: "oasis" },
    { word1: "Coca Cola", word2: "Orangina" },
    { word1: "banque", word2: "casino" },
    { word1: "avion", word2: "hélicoptère" },
    { word1: "avion", word2: "fusée" },
    { word1: "crayon", word2: "stylo" },
    { word1: "école", word2: "bibliothèque" },
    { word1: "voiture", word2: "camion" },
    { word1: "voiture", word2: "moto" },
    { word1: "vélo", word2: "moto" },
    { word1: "forêt", word2: "jungle" },
    { word1: "maison", word2: "appartement" },
    { word1: "ordinateur", word2: "tablette" },
    { word1: "souris", word2: "clavier" },
    { word1: "souris", word2: "rat" },
    { word1: "internet", word2: "wifi" },
    { word1: "stylo", word2: "feutre" },
    { word1: "camion", word2: "bus" },
    { word1: "chien", word2: "loup" },
    { word1: "tigre", word2: "lion" },
    { word1: "fusée", word2: "satellite" },
    { word1: "banque", word2: "coffre" },
    { word1: "vélo", word2: "trottinette" },
    { word1: "poire", word2: "pêche" },
    { word1: "chasse", word2: "pêche" },
    { word1: "casino", word2: "loterie" },
    { word1: "fromage", word2: "camembert" },
    { word1: "pain", word2: "croissant" },
    { word1: "pizza", word2: "quiche" },
    { word1: "gâteau", word2: "tarte" },
    { word1: "poulet", word2: "dinde" },
    { word1: "thon", word2: "sardine" },
    { word1: "lait", word2: "yaourt" },
    { word1: "café", word2: "chocolat chaud" },
    { word1: "café", word2: "jus d'orange" },
    { word1: "eau", word2: "limonade" },
    { word1: "musée", word2: "galerie" },
    { word1: "hôtel", word2: "auberge" },
    { word1: "gare", word2: "station" },
    { word1: "église", word2: "chapelle" },
    { word1: "château", word2: "manoir" },
    { word1: "camping", word2: "caravane" },
    { word1: "plaine", word2: "vallée" },
    { word1: "montagne", word2: "colline" },
    { word1: "lac", word2: "étang" },
    { word1: "village", word2: "bourg" },
    { word1: "médecin", word2: "chirurgien" },
    { word1: "professeur", word2: "instituteur" },
    { word1: "cuisinier", word2: "chef" },
    { word1: "journaliste", word2: "reporter" },
    { word1: "avocat", word2: "notaire" },
    { word1: "policier", word2: "gendarme" },
    { word1: "architecte", word2: "urbaniste" },
    { word1: "peintre", word2: "dessinateur" },
    { word1: "acteur", word2: "comédien" },
    { word1: "musicien", word2: "chanteur" },
    { word1: "football", word2: "rugby" },
    { word1: "tennis", word2: "badminton" },
    { word1: "ski", word2: "snowboard" },
    { word1: "natation", word2: "plongée" },
    { word1: "boxe", word2: "karaté" },
    { word1: "escalade", word2: "alpinisme" },
    { word1: "cyclisme", word2: "VTT" },
    { word1: "danse", word2: "zumba" },
    { word1: "course", word2: "marathon" },
    { word1: "golf", word2: "mini-golf" },
    { word1: "télévision", word2: "écran" },
    { word1: "téléphone", word2: "smartphone" },
    { word1: "lampe", word2: "bougie" },
    { word1: "fauteuil", word2: "canapé" },
    { word1: "clé", word2: "serrure" },
    { word1: "table", word2: "bureau" },
    { word1: "sac", word2: "valise" },
    { word1: "couteau", word2: "fourchette" },
    { word1: "montre", word2: "bracelet" },
    { word1: "lunettes", word2: "jumelles" },
    { word1: "amour", word2: "romance" },
    { word1: "haine", word2: "colère" },
    { word1: "paix", word2: "calme" },
    { word1: "guerre", word2: "conflit" },
    { word1: "travail", word2: "emploi" },
    { word1: "étude", word2: "recherche" },
    { word1: "loisir", word2: "détente" },
    { word1: "rêve", word2: "fantasme" },
    { word1: "peur", word2: "angoisse" },
    { word1: "temps", word2: "météo" },
    { word1: "cheval", word2: "poney" },
    { word1: "oiseau", word2: "moineau" },
    { word1: "poisson", word2: "saumon" },
    { word1: "singe", word2: "gorille" },
    { word1: "ours", word2: "panda" },
    { word1: "chien", word2: "chiot" },
    { word1: "chat", word2: "panthère" },
    { word1: "grenouille", word2: "crapaud" },
    { word1: "serpent", word2: "python" },
    { word1: "cochon", word2: "porc" },
    { word1: "film", word2: "série" },
    { word1: "livre", word2: "bande dessinée" },
    { word1: "musique", word2: "chanson" },
    { word1: "jeu", word2: "puzzle" },
    { word1: "cinéma", word2: "théâtre" },
    { word1: "dessin", word2: "bande dessinée" },
    { word1: "photo", word2: "dessin" },
    { word1: "peinture", word2: "aquarelle" },
    { word1: "concert", word2: "festival" }
];





