export interface MotPair {
    mot1: string;
    mot2: string;
}

export const MOTS: MotPair[] = [

    { mot1: "pomme", mot2: "poire" },
    { mot1: "pomme", mot2: "banane" },
    { mot1: "chat", mot2: "tigre" },
    { mot1: "chat", mot2: "chien" },
    { mot1: "plage", mot2: "désert" },
    { mot1: "plage", mot2: "oasis" },
    { mot1: "Coca Cola", mot2: "oasis" },
    { mot1: "Coca Cola", mot2: "Orangina" },
    { mot1: "banque", mot2: "casino" },
    { mot1: "avion", mot2: "hélicoptère" },
    { mot1: "avion", mot2: "fusée" },
    { mot1: "crayon", mot2: "stylo" },
    { mot1: "école", mot2: "bibliothèque" },
    { mot1: "voiture", mot2: "camion" },
    { mot1: "voiture", mot2: "moto" },
    { mot1: "vélo", mot2: "moto" },
    { mot1: "forêt", mot2: "jungle" },
    { mot1: "maison", mot2: "appartement" },
    { mot1: "ordinateur", mot2: "tablette" },
    { mot1: "souris", mot2: "clavier" },
    { mot1: "souris", mot2: "rat" },
    { mot1: "internet", mot2: "wifi" },
    { mot1: "stylo", mot2: "feutre" },
    { mot1: "camion", mot2: "bus" },
    { mot1: "chien", mot2: "loup" },
    { mot1: "tigre", mot2: "lion" },
    { mot1: "fusée", mot2: "satellite" },
    { mot1: "banque", mot2: "coffre" },
    { mot1: "vélo", mot2: "trottinette" },
    { mot1: "poire", mot2: "pêche" },
    { mot1: "chasse", mot2: "pêche" },
    { mot1: "casino", mot2: "loterie" },
    { mot1: "fromage", mot2: "camembert" },
    { mot1: "pain", mot2: "croissant" },
    { mot1: "pizza", mot2: "quiche" },
    { mot1: "gâteau", mot2: "tarte" },
    { mot1: "poulet", mot2: "dinde" },
    { mot1: "thon", mot2: "sardine" },
    { mot1: "lait", mot2: "yaourt" },
    { mot1: "café", mot2: "chocolat chaud" },
    { mot1: "café", mot2: "jus d'orange" },
    { mot1: "eau", mot2: "limonade" },
    { mot1: "musée", mot2: "galerie" },
    { mot1: "hôtel", mot2: "auberge" },
    { mot1: "gare", mot2: "station" },
    { mot1: "église", mot2: "chapelle" },
    { mot1: "château", mot2: "manoir" },
    { mot1: "camping", mot2: "caravane" },
    { mot1: "plaine", mot2: "vallée" },
    { mot1: "montagne", mot2: "colline" },
    { mot1: "lac", mot2: "étang" },
    { mot1: "village", mot2: "bourg" },
    { mot1: "médecin", mot2: "chirurgien" },
    { mot1: "professeur", mot2: "instituteur" },
    { mot1: "cuisinier", mot2: "chef" },
    { mot1: "journaliste", mot2: "reporter" },
    { mot1: "avocat", mot2: "notaire" },
    { mot1: "policier", mot2: "gendarme" },
    { mot1: "architecte", mot2: "urbaniste" },
    { mot1: "peintre", mot2: "dessinateur" },
    { mot1: "acteur", mot2: "comédien" },
    { mot1: "musicien", mot2: "chanteur" },
    { mot1: "football", mot2: "rugby" },
    { mot1: "tennis", mot2: "badminton" },
    { mot1: "ski", mot2: "snowboard" },
    { mot1: "natation", mot2: "plongée" },
    { mot1: "boxe", mot2: "karaté" },
    { mot1: "escalade", mot2: "alpinisme" },
    { mot1: "cyclisme", mot2: "VTT" },
    { mot1: "danse", mot2: "zumba" },
    { mot1: "course", mot2: "marathon" },
    { mot1: "golf", mot2: "mini-golf" },
    { mot1: "télévision", mot2: "écran" },
    { mot1: "téléphone", mot2: "smartphone" },
    { mot1: "lampe", mot2: "bougie" },
    { mot1: "fauteuil", mot2: "canapé" },
    { mot1: "clé", mot2: "serrure" },
    { mot1: "table", mot2: "bureau" },
    { mot1: "sac", mot2: "valise" },
    { mot1: "couteau", mot2: "fourchette" },
    { mot1: "montre", mot2: "bracelet" },
    { mot1: "lunettes", mot2: "jumelles" },
    { mot1: "amour", mot2: "romance" },
    { mot1: "haine", mot2: "colère" },
    { mot1: "paix", mot2: "calme" },
    { mot1: "guerre", mot2: "conflit" },
    { mot1: "travail", mot2: "emploi" },
    { mot1: "étude", mot2: "recherche" },
    { mot1: "loisir", mot2: "détente" },
    { mot1: "rêve", mot2: "fantasme" },
    { mot1: "peur", mot2: "angoisse" },
    { mot1: "temps", mot2: "météo" },
    { mot1: "cheval", mot2: "poney" },
    { mot1: "oiseau", mot2: "moineau" },
    { mot1: "poisson", mot2: "saumon" },
    { mot1: "singe", mot2: "gorille" },
    { mot1: "ours", mot2: "panda" },
    { mot1: "chien", mot2: "chiot" },
    { mot1: "chat", mot2: "panthère" },
    { mot1: "grenouille", mot2: "crapaud" },
    { mot1: "serpent", mot2: "python" },
    { mot1: "cochon", mot2: "porc" },
    { mot1: "film", mot2: "série" },
    { mot1: "livre", mot2: "bande dessinée" },
    { mot1: "musique", mot2: "chanson" },
    { mot1: "jeu", mot2: "puzzle" },
    { mot1: "cinéma", mot2: "théâtre" },
    { mot1: "dessin", mot2: "bande dessinée" },
    { mot1: "photo", mot2: "dessin" },
    { mot1: "peinture", mot2: "aquarelle" },
    { mot1: "concert", mot2: "festival" }
];





